#### random question

In [4]:
# convert a=[[12,34,45], [34,56,67]] to 5 dim

In [3]:
import numpy as np

arr = np.array([[12, 34, 45], [34, 56, 67]], ndmin=5)
print(arr)
print(arr.shape)

[[[[[12 34 45]
    [34 56 67]]]]]
(1, 1, 1, 2, 3)

## pandas

In [5]:
# create dataframe
import pandas as pd
a = {'id':[1,2,3,4,5],
    'name':['rohit','shruti','anuradha','nayomi','lavanya'],
    'gender':['male','female','female','female','female']}

In [7]:
df = pd.DataFrame(a)
df

   id      name  gender
0   1     rohit    male
1   2    shruti  female
2   3  anuradha  female
3   4    nayomi  female
4   5   lavanya  female

In [8]:
df.head()

   id      name  gender
0   1     rohit    male
1   2    shruti  female
2   3  anuradha  female
3   4    nayomi  female
4   5   lavanya  female

In [11]:
# create a df of 5 employees having their id, name, gender and age
a = {'id':[1.0,2.0,3.0,4.0,5.0],
    'name':['rohit','shruti','anuradha','nayomi','lavanya'],
    'gender':['male','female','female','female','female'],
    'salary': ['95k','90k','70k','75k','80k']}

In [12]:
df = pd.DataFrame(a)
df.head()

    id      name  gender salary
0  1.0     rohit    male    95k
1  2.0    shruti  female    90k
2  3.0  anuradha  female    70k
3  4.0    nayomi  female    75k
4  5.0   lavanya  female    80k

In [13]:
# create a series of names of 6 fruits
f = pd.Series(['Angoor','pineapple','Litchi','Mango','Peru','Apple'])
f

0       Angoor
1    pineapple
2       Litchi
3        Mango
4         Peru
5        Apple
dtype: object

In [19]:
import pandas as pd

df = pd.read_csv("data.csv")
df.head()

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [20]:
# columns >> give names of all columns 
# shape >> gives number of rows and columns
# head >> gives top in rowa 
# tail >> gives bottom n rows 
# loc >> to extract specific rows of specific columns
# info >> give all info about the data 
# describe >> gives statistics values of numeric col
# drop >> to remove rows or cols
# isna >> give count of null values 
# fillna >> used to fill null values 
# dropna >> used to drop rows containing null values
# replace >> used to replace values

In [22]:
df.columns

Index(['Duration', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [23]:
df.shape

(169, 4)

In [24]:
df.head()

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [26]:
df.tail(3)

     Duration  Pulse  Maxpulse  Calories
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [29]:
df.loc[[2,5],['Duration','Pulse']]

   Duration  Pulse
2        60    103
5        60    102

In [30]:
# show the 21,31,41 and 51th row of calories col

df.loc[[21,31,41,51],['Calories']]

    Calories
21     282.0
31     180.1
41     286.0
51     643.1

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB

In [32]:
df.describe()

         Duration       Pulse    Maxpulse     Calories
count  169.000000  169.000000  169.000000   164.000000
mean    63.846154  107.461538  134.047337   375.790244
std     42.299949   14.510259   16.450434   266.379919
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.925000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   387.600000
max    300.000000  159.000000  184.000000  1860.400000

In [33]:
df.drop(index = [1,2,3], axis=0,inplace=True)
# axis =0 used for rows  and 1 for col  , inplace = True used for permanent removal
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[166 rows x 4 columns]

In [34]:
df.drop(labels = ['Pulse'],axis=1,inplace=True)
df

     Duration  Maxpulse  Calories
0          60       130     409.1
4          45       148     406.0
5          60       127     300.0
6          60       136     374.0
7          45       134     253.3
..        ...       ...       ...
164        60       140     290.8
165        60       145     300.0
166        60       145     310.2
167        75       150     320.4
168        75       150     330.4

[166 rows x 3 columns]

In [36]:
# remove calories col
df.drop(labels=['Calories'],axis=1,inplace = True )
df

     Duration  Maxpulse
0          60       130
4          45       148
5          60       127
6          60       136
7          45       134
..        ...       ...
164        60       140
165        60       145
166        60       145
167        75       150
168        75       150

[166 rows x 2 columns]

In [37]:
# remove 4th and 7th row from data
df.drop(index = [4,7], axis = 0,inplace = True)
df

     Duration  Maxpulse
0          60       130
5          60       127
6          60       136
8          30       133
9          60       124
..        ...       ...
164        60       140
165        60       145
166        60       145
167        75       150
168        75       150

[164 rows x 2 columns]

In [38]:
df.isna().sum()

Duration    0
Maxpulse    0
dtype: int64

In [ ]:
# fillna
# if datatype of col is numeric then we fill null values by mean/median of that col
# if datatype of col is obj then we fill it by mode (most repeated values) of that col
# if null values are more than 40% then we drop it
# df[col].fillna(df[col].mean(),inplace=True)  for numeric
# df[col].fillna(df[col].mode()[0],inplace=True)  for object col

In [39]:
# dropna  >> drops the null values
df.dropna()

     Duration  Maxpulse
0          60       130
5          60       127
6          60       136
8          30       133
9          60       124
..        ...       ...
164        60       140
165        60       145
166        60       145
167        75       150
168        75       150

[164 rows x 2 columns]

In [42]:
# replace >> to replace values
# f[col].replace([old_value1, old_value2],[new_value1,new_value2], inplace = True)

In [43]:
# create a df having info of your 5 family members with their id,name,age and gender
import pandas as pd

data = {
    "ID": [1, 2, 3, 4, 5],
    "Name": ["Father", "Mother", "Brother", "Sister", "Me"],
    "Age": [48, 45, 22, 18, 20],
    "Gender": ["Male", "Female", "Male", "Female", "Female"]
}

df = pd.DataFrame(data)
print(df)

   ID     Name  Age  Gender
0   1   Father   48    Male
1   2   Mother   45  Female
2   3  Brother   22    Male
3   4   Sister   18  Female
4   5       Me   20  Female

In [44]:
# show the top two rows
df.head(2)

   ID    Name  Age  Gender
0   1  Father   48    Male
1   2  Mother   45  Female

In [45]:
# show the names of all col
df.columns

Index(['ID', 'Name', 'Age', 'Gender'], dtype='object')

In [46]:
# show the 2nd and 4th row of name and age
df.loc[[2,4],['Name','Age']]

      Name  Age
2  Brother   22
4       Me   20

In [48]:
# check null values in data
df.isna().sum()

ID        0
Name      0
Age       0
Gender    0
dtype: int64

In [49]:
# show the num of rows and cols
df.shape

(5, 4)

In [51]:
# show the info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      5 non-null      int64
 1   Name    5 non-null      object
 2   Age     5 non-null      int64
 3   Gender  5 non-null      object
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [54]:
# remove the 4th row
df.drop(index = [4],axis=0,inplace=True)
df

KeyError: '[4] not found in axis'

In [ ]:
# remove col gender
df.drop(labels = ['Gender'],axis=1,inplace=True)
df